name: Run

on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '30 1 * * *' # 每天9:30, 14:30执行，时间为国际标准时间 + 8 =北京时间！！

jobs:
  build:

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Run
      uses: coactions/setup-xvfb@main
      with:
        run: dotnet run
      env: 
        CONF: ${{ secrets.CONF }}
